In [1]:

from google.colab import files 
  
  
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.3.0'

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [4]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [5]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
X[:,1:5]

array([[0.0, 0.0, 619, 0],
       [0.0, 1.0, 608, 0],
       [0.0, 0.0, 502, 0],
       ...,
       [0.0, 0.0, 709, 0],
       [1.0, 0.0, 772, 1],
       [0.0, 0.0, 792, 0]], dtype=object)

In [10]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [11]:

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [18]:
model = tf.keras.models.Sequential()

In [19]:

# Adding the input layer and the first hidden layer
model.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer
model.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [20]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [21]:
model.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 948us/step - loss: 0.5800 - accuracy: 0.7089
Epoch 2/100
250/250 [==============================] - 0s 866us/step - loss: 0.4680 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 844us/step - loss: 0.4488 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 860us/step - loss: 0.4402 - accuracy: 0.7961
Epoch 5/100
250/250 [==============================] - 0s 846us/step - loss: 0.4360 - accuracy: 0.7964
Epoch 6/100
250/250 [==============================] - 0s 943us/step - loss: 0.4328 - accuracy: 0.7965
Epoch 7/100
250/250 [==============================] - 0s 856us/step - loss: 0.4307 - accuracy: 0.7969
Epoch 8/100
250/250 [==============================] - 0s 865us/step - loss: 0.4292 - accuracy: 0.7970
Epoch 9/100
250/250 [==============================] - 0s 875us/step - loss: 0.4278 - accuracy: 0.7972
Epoch 10/100
250/250 [==============================] - 0s 907us/step - l

In [22]:
print(model.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [17]:
# Predicting the Test set results
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [23]:

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1486  109]
 [ 183  222]]


0.854